### ISSUE TITLE
Request - interactive demo

### ISSUE THREAD

**Issue by adsteel** [jasonslyvia/react-anything-sortable#14]
I've been trying to figure out which library I might use for this functionality, but most of them have issues on touch screens. An interactive demo will help folks choose the right library.

**Comment by jasonslyvia** [comment]
Fair enough, demo will be online soon.

**Comment by jasonslyvia** [comment]
[http://jasonslyvia.github.io/react-anything-sortable/demo/index.html](http://jasonslyvia.github.io/react-anything-sortable/demo/index.html)

There you go!

**Comment by jasonslyvia** [comment]
BTW, I've tested it and there is no touch screen support at this point :(

**Comment by adsteel** [comment]
Thanks for the speedy response!

**Comment by jasonslyvia** [comment]
I've added touch event support since v1.1.0 if you're still interested, let me know what you think.

**Comment by adsteel** [comment]
@jasonslyvia Impressive your speed is. I checked out the demo, it looks good, but I wonder how it would handle scrolling on a longer sortable list (my particular need right now). May need to add a customizable delay-to-drag, and confirm in a more complex demo.

**Comment by jasonslyvia** [comment]
That's a toughie I think, I'll dig into it later. I'm sorry this repo doesn't suit your needs.

**Comment by skitterm** [comment]
Ditto that handling scrolling on the reorderable list would be a big win. It works when the list is full-page-height, but when it is scrollable inside of a div or something it won't let me drop the dragged item where I want.
