### ISSUE TITLE
onSort passed in the sortData of the item that was moved

### ISSUE THREAD

**Issue by jakobwilkenson** [jasonslyvia/react-anything-sortable#17]
Sorry, saw you were working on the library right now so figured I'd ask if you have any clue what could be causing this. I'm using React 0.14.1. The error happens inside require('react-anything-sortable').

window.ReactDOM = require('react-dom');
var SortableMixin = require('react-anything-sortable').SortableItemMixin;

Thanks

**Comment by jasonslyvia** [comment]
Hi @jakobwilkenson , which version of `react-anything-sortable` are you using?

**Comment by jakobwilkenson** [comment]
Thanks for responding. I'm using 1.1.1.

**Comment by jasonslyvia** [comment]
Do you mind give `1.1.2` a try because I believe I make some build mistake in `1.1.1`.

**Comment by jakobwilkenson** [comment]
Thanks Jason! 1.1.2 works for me.

**Comment by jakobwilkenson** [comment]
A quick recommendation now that I have it working. The integration would be significantly easier if onSort passed in the sortData of the item that was moved as well as the array or ordered sort datas. Since I don't want to submit the whole list to the server every time it means that I now have to diff the list form before/after to figure out what changed.

startedDragging/stoppedDragging  callbacks would also be helpful but not at all as critical.

Thanks for the great library!

**Comment by jasonslyvia** [comment]
So are you suggesting return a object for `onSort`? Or maybe adding another callback props to do this job.

**Comment by jakobwilkenson** [comment]
My suggestion would be to return an object in onSort.

**Comment by jasonslyvia** [comment]
I'm sorry for the long delay, thanks to  @jakubruffer this feature is implemented in a way adding more parameters in `onSort` callback.

You can test it out in version `1.4.3`.
