### ISSUE TITLE
Flicking when dragging final Items

### ISSUE THREAD

**Issue by hfcorreia** [jasonslyvia/react-anything-sortable#18]
In the demo, there is a small glitch/flicking of the first item when you drag the last item.

Maybe the first items are being unnecessarily rendered?

**Comment by jasonslyvia** [comment]
I can't reproduce your problem, which browser and platform are you using?

**Comment by hfcorreia** [comment]
I'm using Mac OS X and it happens both in Safari and Chrome.

**Comment by evanc** [comment]
I actually see it any time I try to drag anything but the first item *left*:

![draggable](https://cloud.githubusercontent.com/assets/58823/12520391/16c909d4-c0f9-11e5-90f7-7885ed420aa0.gif)

Chrome 47.0.2526.111 on OS X 10.10.

**Comment by evanc** [comment]
hm going frame-by-frame it looks like the flicker is the "placeholder" being added to the markup in the wrong place:
![draggable-flicker](https://cloud.githubusercontent.com/assets/58823/12520625/79ffab7e-c0fa-11e5-99a9-bbce1625d65a.gif)

**Comment by jasonslyvia** [comment]
That's very helpful @evanc , I can reproduce it now.

Thanks guys, a fix will be made soon.

**Comment by jasonslyvia** [comment]
Please try version 1.3.2.

I've also added some tests for this situation. 

https://github.com/jasonslyvia/react-anything-sortable/blob/eb8bd5e03f64bbd827b10647471bc84aa3fa2d37/test/specs/sortable-test.js#L158
