### ISSUE TITLE
Limit Draggable Area

### ISSUE THREAD

**Issue by hfcorreia** [jasonslyvia/react-anything-sortable#19]
Is it possible to limit the area that an user can drag an item? It would be nice to define boundaries in which you could drag an item. 

Is this in your plans? Is it difficult to add support for this?

**Comment by jasonslyvia** [comment]
I guess I can add an option which only allow dragging inside `Sortable` container, does it sound OK to you?

**Comment by hfcorreia** [comment]
Yes, that seems the desired behaviour.

**Comment by jasonslyvia** [comment]
This will be released in next version :)

**Comment by hfcorreia** [comment]
Do you have any idea of when you'll have the next release?

**Comment by jasonslyvia** [comment]
My procrastination told me maybe in a week.

**Comment by jasonslyvia** [comment]
Hi @hfcorreia , can you please try 1.2.0 for this feature.

http://jasonslyvia.github.io/react-anything-sortable/demo/index.html#react4

**Comment by hfcorreia** [comment]
Seems okay! Many Thanks :+1:

**Comment by jasonslyvia** [comment]
With pleasure :)
