### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by ivdma** [jasonslyvia/react-anything-sortable#2]
Would love to be able to use this package via Bower.

**Comment by jasonslyvia** [comment]
I'm considering a refactor which involves removing jQuery and add more tests, I believe a new version will be published in Sunday. Of course bower package will be added too, please be patient.

**Comment by ivdma** [comment]
Awesome!

**Comment by jasonslyvia** [comment]
bower package released in `0.2.0`

**Comment by vizath** [comment]
There is a typo in the bower installation process in the readme.
`bower install react-anythOng-sortable`

**Comment by jasonslyvia** [comment]
@vizath sweet, will fix in soon.
