### ISSUE TITLE
React can't find the root component node for data-reactid value `.5`.

### ISSUE THREAD

**Issue by styks1987** [jasonslyvia/react-anything-sortable#20]
Only after loading your component I get React can't find the root component node for data-reactid value `.5`.

Loading via requirejs data-main attribute. 

<img width="771" alt="screen shot 2015-12-10 at 11 53 50 am" src="https://cloud.githubusercontent.com/assets/642930/11722017/b59df998-9f34-11e5-9847-e5fb406fdd2c.png">
<img width="514" alt="screen shot 2015-12-10 at 11 53 04 am" src="https://cloud.githubusercontent.com/assets/642930/11722016/b59d0736-9f34-11e5-9fab-841d698a4e50.png">
<img width="862" alt="screen shot 2015-12-10 at 11 52 56 am" src="https://cloud.githubusercontent.com/assets/642930/11722018/b5a2b30c-9f34-11e5-92e1-f6d742f37fd5.png">
<img width="388" alt="screen shot 2015-12-10 at 11 52 08 am" src="https://cloud.githubusercontent.com/assets/642930/11722014/b59c3fe0-9f34-11e5-8fb8-23558a1e73f5.png">
<img width="466" alt="screen shot 2015-12-10 at 11 51 57 am" src="https://cloud.githubusercontent.com/assets/642930/11722015/b59cdfc2-9f34-11e5-86b8-2e0a1984940a.png">

**Comment by jasonslyvia** [comment]
That's weird, do you mind adding some working snippet or demo repo which I can reproduce this issue?

**Comment by jasonslyvia** [comment]
I'm closing this issue until more details are provided.
