### ISSUE TITLE
when dynamically add new SortableItem,  the page did not show the new item

### ISSUE THREAD

**Issue by flappymonkey** [jasonslyvia/react-anything-sortable#21]

**Comment by jasonslyvia** [comment]
Do you use a new `key` on `Sortable` ? Please check the dynamic demo for more details.

**Comment by jasonslyvia** [comment]
http://jasonslyvia.github.io/react-anything-sortable/demo/index.html

**Comment by flappymonkey** [comment]
thanks, it's ok when add new key on Sortable.
