### ISSUE TITLE
Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by smadapathi** [jasonslyvia/react-anything-sortable#24]
We are facing this issue when we have added this plugin. When we remove this plugin, it is working fine. On search, we can notice that it happens because of multiple reactjs versions.
http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined
In bower.json, we can see this, is it the source of the issue?
```javascript
"dependencies": {
    "react": "*"
  }
```
Also, we are using react version 0.13.3, react-anything-sortable 0.3.2
Thanks in Advance!

**Comment by jasonslyvia** [comment]
How do you build your project?

**Comment by smadapathi** [comment]
Using gulp

**Comment by jasonslyvia** [comment]
Can you post your build script, I still can't figure out how you use this library.

`React` is listed as `peerDependencies` in `package.json`, which means React is not bundled with `react-anything-sortable` by default.

**Comment by smadapathi** [comment]
Ok, I have fixed this issue by putting react-addons in externals of webpack config. 
Before the fix it was like this 
```Javascript
 externals: {
   '/$^/': 'commonjs',
   'react': 'var window.React',
   'react-router': 'var window.ReactRouter'
}
```
After the fix, it is like this
```Javascript
externals: {
     '/$^/': 'commonjs',
     'react': 'var window.React',
     'react-router': 'var window.ReactRouter',
     'react/addons': 'var window.React',
     'react/addons/lib': 'react/../lib'
    }
```

**Comment by jasonslyvia** [comment]
Cool.

**Comment by smadapathi** [comment]
Thanks for your time and thanks for this plugin :+1:
