### ISSUE TITLE
ie8下，会报出“类型不匹配”的错误

### ISSUE THREAD

**Issue by wp2123** [jasonslyvia/react-anything-sortable#25]
如题，在ie8下引用会报出“类型不匹配”的错误。

我跟进了一下，发现off方法传入的callback有时为空，有可能是这个原因引起的。
http://stackoverflow.com/questions/31971004/ie8-compatibility-mode-type-mismatch-detachevent

**Comment by jasonslyvia** [comment]
谢谢！是否考虑提个 PR？

**Comment by wp2123** [comment]
待我研究一下哈 :)

**Comment by jasonslyvia** [comment]
issue 暂时关闭，如果有 pr 的话再重新开启。
