### ISSUE TITLE
Can not sort item with state

### ISSUE THREAD

**Issue by pingyuanChen** [jasonslyvia/react-anything-sortable#28]
eg: 
return this.renderWithSortable(
      <div>
        <span>{this.state.sheetName}</span>
      </div>
    );

Like this, sort is not working

**Comment by jasonslyvia** [comment]
try wrap `this.state.sheetName` into `<span>` or other tags like this

```javascript
return this.renderWithSortable(
  <span>{this.state.sheetName}</span>
);
```

**Comment by pingyuanChen** [comment]
I do wrap this.state.sheetName with tag:
`return this.renderWithSortable(
      <div>
        <span>{this.state.sheetName}</span>
      </div>
    `);

**Comment by jasonslyvia** [comment]
I need more context, is there any error in console? is there anything rendered in DOM? More code snippets would be helpful.

**Comment by pingyuanChen** [comment]
I try some simple example, it also doesn't work, I think something about this.state object:
```javascript
var SheetItem = React.createClass({
  mixins: [SortableItemMixin],

  getInitialState: function(){
    return {
      testName: this.props.name
    };
  },
  render: function(){
    return this.renderWithSortable(
      <div>
        <span>{this.state.testName}</span>
      </div>
    );
  }
});

opsDom = sortedOps.map(function(item, index){
      var attrs = item.getAttributes(),
        key = attrs.id || 0;
      return <SheetItem
               key={index}
               name={index}
               sortData={index} />;
    }.bind(this));
```

**Comment by jasonslyvia** [comment]
By saying `doesn't work`, do you mean nothing is rendered, or the rendered items can not be sorted, can you elaborate?

**Comment by pingyuanChen** [comment]
Sorry, it can be rendered, but can not be sorted.

**Comment by jasonslyvia** [comment]
Have you added necessary styles? Check out [this](https://github.com/jasonslyvia/react-anything-sortable/blob/master/demo/style.css) for reference.

**Comment by jasonslyvia** [comment]
Closed for no further information provided.
