### ISSUE TITLE
Disabled Property

### ISSUE THREAD

**Issue by onzag** [jasonslyvia/react-anything-sortable#30]
Why don't you have a property that is able to disable the sortable element? sometimes you have so many elements on the screen and then scrolling on a mobile device becomes impossible, it'll be good to just be able to disable the sorting as needed.

**Comment by jasonslyvia** [comment]
Hi @onzag , can you check if @zthomas 's solution works for you too? 

https://github.com/jasonslyvia/react-anything-sortable/pull/33

**Comment by jasonslyvia** [comment]
I've added a [demo](http://jasonslyvia.github.io/react-anything-sortable/demo/#/handle) here.

**Comment by onzag** [comment]
That works Thanks!
