### ISSUE TITLE
Need to disable default scrolling for touch based mobile devices

### ISSUE THREAD

**Issue by zthomas** [jasonslyvia/react-anything-sortable#31]
On the demo you can see that if you drag and sort an item vertically it triggers the native scrolling behaviour making it completely unusable. 

I have a PR for a simple fix. 
https://github.com/jasonslyvia/react-anything-sortable/pull/32

**Comment by jasonslyvia** [comment]
merged and confirmed working, thanks @zthomas

**Comment by jasonslyvia** [comment]
Hi @zthomas , just a heads up, I've refactor your PR to move the `sortHandleClass` props to `<Sortable>` and renamed it to `sortHandle`.

https://github.com/jasonslyvia/react-anything-sortable/blob/140b55cdf1256b6e6e7e2594bb50c6366108f201/demo/pages/handle.js

**Comment by zthomas** [comment]
cool, looks great!
