### ISSUE TITLE
Error on drag when sortHandle contains an SVG

### ISSUE THREAD

**Issue by antialiasis** [jasonslyvia/react-anything-sortable#34]
My sortHandle is a span containing an SVG icon, but when I try to drag on it, I get this error: `Uncaught TypeError: e.target.className.indexOf is not a function`

The culprit is [this line](https://github.com/jasonslyvia/react-anything-sortable/blob/master/src/SortableItemMixin.js#L9); for an SVG, the className is not a string but an SVGAnimatedString object, which does not have an indexOf property. This case should probably be handled somehow.

**Comment by jasonslyvia** [comment]
Yeah, thanks for your digging, will be fixed soon.

**Comment by jasonslyvia** [comment]
By the way, is your `sortHandle` defined on a SVG element?

**Comment by antialiasis** [comment]
No, it's a span that contains the SVG.

**Comment by jasonslyvia** [comment]
Hi, `1.4.2` should resolve this issue, and here is [related test suite](https://github.com/jasonslyvia/react-anything-sortable/blob/master/test/specs/sortable-test.js#L485).

**Comment by antialiasis** [comment]
Excellent, thanks for the swift fix.
