### ISSUE TITLE
warning.js:45 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Sortable component.

### ISSUE THREAD

**Issue by dineshi2it** [jasonslyvia/react-anything-sortable#35]
Just cloned the repo and ran 
1. npm install, 
2. npm demo:watch

After I drag and drop an item I get this warning.
![sort_set_state_err](https://cloud.githubusercontent.com/assets/5243459/14559883/7d408a9e-0329-11e6-924a-c9afcc0b867f.png)

**Comment by jasonslyvia** [comment]
Yeah it's a edge case, previously I used `this.isMounted()` to check whether the instance is mounted, but it's discouraged by React and will be deprecated soon. 

So figuring out a new way to do this check now.

**Comment by jasonslyvia** [comment]
should be fixed in 21f0d27562e2f5d6cb34ffabafd7af2f340c2ddc

**Comment by dineshi2it** [comment]
Right now I have added 0 setTimeout like this:

```
  handleSort(sortedArray) {
    this._sortableKey++;
    setTimeout((function () {
      this.setState({
        arr: sortedArray
      });
    }).bind(this), 0);
  }
```

**Comment by jasonslyvia** [comment]
Can you pull the master and try run `demo:watch` again to see if this problem persists?

**Comment by dineshi2it** [comment]
Yeah, that works fine without any warning :+1:. Waiting for the release now.
