### ISSUE TITLE
outerWidth and outerHeight include margins

### ISSUE THREAD

**Issue by ivdma** [jasonslyvia/react-anything-sortable#4]
Maybe it's more a question than a bug

When draggable element is cloned, outerWidth and outerHeight of the new element include the margins of the original element. I have margins between my items. So when I drag one element it becomes big and ugly.

Why did you choose to use outerWidth with margins? Is it by design or to fix quirks of bad browsers?

I experience it in Chrome, Safari, Firefox and IE8 on XP.

Can I help improve it?

**Comment by jasonslyvia** [comment]
This behaviour has been corrected in version `0.2.0`, previously I use `width/height with margin` to calculate the coordinates that determine when should two elements swap position.
