### ISSUE TITLE
The suggested solution for dynamic children involving changing the key of the Sortable component is less than ideal

### ISSUE THREAD

**Issue by antialiasis** [jasonslyvia/react-anything-sortable#46]
Hello. I've got some sortable items that perform some work on componentDidMount that may change their dimensions. I am also dynamically adding and removing sortable items, as well as changing their order by other means than dragging, so I have been using the recommended solution of giving the Sortable component a key and incrementing it whenever the items change.

However, this means that React will unmount and remount the entire list every time I sort - which leads to those elements rerunning their componentDidMount, performing a bunch of unnecessary work and to boot changing their dimensions, causing jank. In general, this definitely doesn't seem like an ideal solution - it'd also mean uncontrolled inputs getting cleared, etc. Is there no better way to update the item list than the key hack?

**Comment by jasonslyvia** [comment]
It's been discussed in #15 , and to solve this problem without `key` would be tricky, which I don't have much time to invest for now. Feel free to send a PR if you have an idea about how it can be done.

**Comment by jasonslyvia** [comment]
released `1.5.0`
