### ISSUE TITLE
getComputedStyle is not defined

### ISSUE THREAD

**Issue by ctxhou** [jasonslyvia/react-anything-sortable#50]
Hi, when I use shallow render to test my react component, it show `getComputedStyle is not defined`.

And I find it doesn't define at [/src/utils.js#L55](https://github.com/jasonslyvia/react-anything-sortable/blob/b94aae8912490c04fd6aa0896568a8a06cff0e1c/src/utils.js#L55).

**Comment by jasonslyvia** [comment]
`getComputedStyle` is one of `window`'s method, you have to use something like jsdom to provide a browser envrionment or just mock it.

**Comment by ctxhou** [comment]
Got it!

Thanks.
