### ISSUE TITLE
Demo broken ??

### ISSUE THREAD

**Issue by sahanDissanayake** [jasonslyvia/react-anything-sortable#52]
Nothing is happening
<img width="737" alt="screen shot 2016-06-20 at 2 54 32 am" src="https://cloud.githubusercontent.com/assets/5580680/16178043/6c54a624-3692-11e6-91b6-d9a47604af47.png">

**Comment by jasonslyvia** [comment]
It works on Chrome 51, which browser are you using? Is there any error in console?

**Comment by sahanDissanayake** [comment]
No errors in console

"5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

**Comment by sahanDissanayake** [comment]
OH my god. Sorry. I did not click on the link.. I tried to moved the links up and down.. Its been a long night.. damn.. sorry

**Comment by jasonslyvia** [comment]
No problem dude, take some rest :)
