### ISSUE TITLE
Vertical demo doesn't appear to use "direction: vertical"

### ISSUE THREAD

**Issue by tnrich** [jasonslyvia/react-anything-sortable#53]
https://github.com/jasonslyvia/react-anything-sortable/blob/master/demo/pages/vertical.js

I am not sure what the desired behavior is here, but it doesn't seem like the demo conforms to the docs:
![image](https://cloud.githubusercontent.com/assets/2730609/16276441/3a3e6cd8-3863-11e6-9167-8d7d1a8cf3aa.png)

It appears maybe this is the code for the "Using decorators" example
![image](https://cloud.githubusercontent.com/assets/2730609/16276545/acee3916-3863-11e6-9490-7575e6fe7ccf.png)

Cheers,
Thomas

**Comment by jasonslyvia** [comment]
Hi @tnrich , you have such keen observation! The demo is updated, thanks.
