### ISSUE TITLE
Can't use cmd+a inside a sortable component

### ISSUE THREAD

**Issue by vhpoet** [jasonslyvia/react-anything-sortable#57]
I have a textarea inside a component wrapped by `@sortable` and I can't use the `cmd+a` (which is supposed to "Select All" text inside the textarea). Removing the `@sortable` decorator fixes the `cmd+a`. I'm guessing `sortable` is preventing some keyboard events.

**Comment by jasonslyvia** [comment]
The only two event handlers `sortable` interfere with are `onMouseDown` and `onTouchStart`, maybe a working demo might help debugging.

**Comment by olesse** [comment]
Having this issue as well. @vhpoet, did you find anything?

**Comment by vhpoet** [comment]
Didn't have time to check it yet @jasonslyvia @olesse

**Comment by hvergara** [comment]
It's related with **selectstart** event capture, on SortableItemMixin.js

`
 on(node, 'selectstart', (e) => {
    if (e.preventDefault) {
      e.preventDefault();
    } else {
      e.returnValue = false;
    }
  });
`

**Comment by jasonslyvia** [comment]
@hvergara yes, this is intended for legacy IEs, i guess we can remove it safely now.

**Comment by jasonslyvia** [comment]
I made a pull request to remove this prevention, but I got another dilemma, hope you guys can help. #63

**Comment by jasonslyvia** [comment]
can you guys confirm whether it's been settled or not in `1.6.1`?

**Comment by vhpoet** [comment]
@jasonslyvia will check today and let you know

**Comment by vhpoet** [comment]
@jasonslyvia works! Thank you.
