### ISSUE TITLE
"Warning: Unknown props `sortData`, `onSortableItemMount`..." on initial render with React 1.5.2

### ISSUE THREAD

**Issue by peletiah** [jasonslyvia/react-anything-sortable#58]
I've upgraded from Babel 5 to Babel 6 and transpile the [vertical-demo](http://jasonslyvia.github.io/react-anything-sortable/demo/#/vertical?_k=ewrtzi) with the help of "[transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy)"-plugin (Babel 6 currently [does not support decorators](http://babeljs.io/docs/plugins/transform-decorators/)):
```javascript
import React from 'react';
import Sortable from 'react-anything-sortable';
import { sortable } from 'react-anything-sortable';

@sortable
class DemoHOCItem extends React.Component {
  render() {
    return (
      <div {...this.props}>
        {this.props.children}
      </div>
    );
  }
}

export default DemoHOCItem;

class Test extends React.Component {
  constructor() {
    super();
    this.state = {
      items: ['four','five','six']
    };
  }

render() {
    function renderWithSortable(renderItem, index) {
      return (
        <DemoHOCItem className="vertical" sortData="renderItem" key={index} dynamic>
          {console.log('rendering with sortable')}
          {renderItem+' sortable'}
        </DemoHOCItem>
      );
    }

    return (
      <div className="demo-container">
         <Sortable className="vertical-container" direction="vertical">
          {this.state.items.map(renderWithSortable, this)}
        </Sortable>
      </div>
    );
  }
};

export default Test;
```

On the initial rendering of ```<DemoHOCItem/>``` I get this warning:

```javascript
main.js:28024 Warning: Unknown props `sortData`, `onSortableItemMount`, `onSortableItemReadyToMove`, `sortable`, `sortHandle` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by DemoHOCItem)
    in DemoHOCItem (created by SortableItem)
    in SortableItem (created by Test)
    in div (created by Sortable)
    in Sortable (created by Test)
    in div (created by Test)
    in Test (created by RoutingContext)
    in div (created by App)
    in App (created by RoutingContext)
    in RoutingContext (created by Router)
    in Router
```

also when dragging an sortable item for the first time:

```javascript
main.js:28024 Warning: Unknown prop `isDragging` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by DemoHOCItem)
    in DemoHOCItem (created by SortableItem)
    in SortableItem (created by Test)
```
Subsequent renderings (Without reloading the app) no longer produce warnings, so the sortable-module works despite the warnings.

I figured the issue is with the aforementioned babel-plugin, and [filed a bug report](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/38), but the author thinks it's rather related to react-sortable-anything:

> Have you filed this issue with that module? It seems more likely to be that they are passing the props down into the child component incorrectly somewhere.

**Comment by jasonslyvia** [comment]
I guess this is introduced by React v15.2.0, which no longer allow unknown properties for DOM elements.

https://github.com/facebook/react/blob/master/CHANGELOG.md

**Comment by jasonslyvia** [comment]
If you're hurry to use this library, try installing React under v15.2 for now.

**Comment by peletiah** [comment]
I can live with the warnings for now. Thanks for the heads-up!

**Comment by Darmody** [comment]
@peletiah just don't pass all props to div tag, only pass useful ones. #59 
@jasonslyvia what do you think?

**Comment by jasonslyvia** [comment]
I guess that's what React wishes us to do.

https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by peletiah** [comment]
@Darmody The props are passed by ```SortableItem```, so I can't really influence it, here's the full warning:

```javascript
warning.js:44 Warning: Unknown props `sortData`, `sequenceField`, `onSortableItemMount`, `onSortableItemReadyToMove`, `sortable`, `sortHandle` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Sequence)
    in Sequence (created by SortableItem)
    in SortableItem (created by renderSequences)
warning	@	warning.js:44
```

**Comment by Darmody** [comment]
@peletiah What the #59 PR doing is removing the unknown props you mentioned. Actually just four props are useful.All props appeared in the warning are unnecessary.

**Comment by peletiah** [comment]
Yep, just realized what you mean :-)
