### ISSUE TITLE
Allow the number of elements to change overtime

### ISSUE THREAD

**Issue by vizath** [jasonslyvia/react-anything-sortable#6]
Is it possible to update the items that can be sortable at runtime ?
For example, a button that add an element to be ordered.

It doesn't seem possible, since `_dimensionArr` and `_orderArr` are set only in `getInitialState()` and every operation seem to be based on their indexes.

Thanks.

**Comment by yangit** [comment]
Hi,
You can use `key` property of <Sortable> to force react to reinitialise the component.
If you have component with `items` property you can do this:

````
render (
<Sortable key={this.state.items.length}>
<YourComponent />
<YourComponent />
</Sortable>
)
````
Every time there is new item in this.state.items you'll get key property changed. And react will call `getInitialState()`  and render `<Selectable>` again.

**Comment by jasonslyvia** [comment]
Basically @yangit  is right, since `SortableItem`s were passed as `children` to `Sortable`, there is no way `Sortable` can maintain the mutation among the children.
