### ISSUE TITLE
SortableContainer is not exported

### ISSUE THREAD

**Issue by m90** [jasonslyvia/react-anything-sortable#62]
I am trying to use the container based approach described in the README, yet the module does not seem to export the required `<SortableContainer />` component.

I am trying the following:
```jsx
import React from 'react';
import {SortableContainer} from 'react-anything-sortable';

export const Item = ({
	thing
}) => (
	<SortableContainer sortData={thing}>
		<li className='list-item'>
			{thing}
		</li>
	</SortableContainer>
);
```

but `SortableContainer` is `undefined`.

When I iterate over the keys of the default export I get:

```
"displayName", "propTypes", "SortableItemMixin", "sortable"
```

so it looks like it's not being exported.

The weird thing is that looking at the files installed into my `node_modules` the file that `main` points to does not say anything about a `SortableContainer`:

```
frederik@thinkpad[lib](some-branch) $ cat index.js | grep SortableContainer
frederik@thinkpad[lib](some-branch) $ 
```

The version I installed is `1.5.2`

**Comment by jasonslyvia** [comment]
sorry this feature was not released, please try version `1.6.0`.

**Comment by m90** [comment]
Ok, exports as expected now, thanks for the insanely fast release!

**Comment by jasonslyvia** [comment]
No problem 😉
