### ISSUE TITLE
use callbackfunction to set father's state, dragEvent doesn't work

### ISSUE THREAD

**Issue by mylesshie** [jasonslyvia/react-anything-sortable#64]
In father:

  sortCallback( data ) {
    let { sortModal } = this.state
  	sortModal.sortList = data
  	console.log( sortModal )
    // this.setState({
    // 	sortList: data
    // })
  }
<SortItemList key={new Date().getTime()} data={imgList} sortCallback={this.sortCallback} />

In self:

  handleSort( data ) {
    const { sortCallback } = this.props 
    if( sortCallback ){
      sortCallback( data )
    }
  }
<div className="demo-container">
        <p className="sort-result">{this.state.result}</p>
        <Sortable dynamic={true} key={new Date().getTime()} onSort={this.handleSort.bind(this)}>
          {itemList}
        </Sortable>
      </div>

when I want setState in sortCallback(), the sortEvent doesn't work, when I remove  setState, It work well

Thank  you! My English is poor.......

**Comment by jasonslyvia** [comment]
用中文 ok 的 😉

要不你重新描述一下你的问题，代码贴完整一点？

**Comment by mylesshie** [comment]
- -，，，，
我在父组件里面有一个callback方法传递给子组件，在sortable的handleSort方法中执行，如果我的父组件的callback方法中有setState在每次排序结束会设置父state的一个状态，则sortable的拖动排序会无效，但是也没有报错，如果去掉setState的代码则拖动正常
大概就是这个意思，

**Comment by jasonslyvia** [comment]
试试 `<Sortable dynamic>`

**Comment by jasonslyvia** [comment]
closing for no further update
