### ISSUE TITLE
Drag into other Sortable divs

### ISSUE THREAD

**Issue by kespindler** [jasonslyvia/react-anything-sortable#66]
I'm wondering if you have tried to get react-anything-sortable to work with multiple target Sortable divs.

My specific use case is that I want to be able to drag items to re-order within a list, but also have the ability to drag the items into labels/buckets.

**Comment by jasonslyvia** [comment]
It's currently unsupported, as for this feature, maybe [react-dnd](https://github.com/gaearon/react-dnd) worth a shot, it's more complex but more flexible.

**Comment by kespindler** [comment]
Woah. That's a great lib, thanks for the reference.
