### ISSUE TITLE
Errors when using in browserify

### ISSUE THREAD

**Issue by juliankrispel** [jasonslyvia/react-anything-sortable#8]
I'm getting the following compile error when I try to use this with browserify: 
`Cannot find module 'babelify' from '/Users/juliiankrispel/projects/Rainforest/node_modules/react-anything-sortable`

**Comment by jasonslyvia** [comment]
Hi, can you elaborate how you use browserify with this module?

**Comment by dreamedits** [comment]
add babelify dependency

**Comment by juliankrispel** [comment]
Adding babelify fixed the compile errrors

**Comment by jamayka** [comment]
There is `"main": "lib/index.js"` in package.json. And then in browserify section babelify is specified as transform filter for this file. Why? lib/index.js is pure JS, isn't it?

**Comment by jasonslyvia** [comment]
Yeah, I guess I don't really figure out the way `package.json` works, I'll look into it soon. Thanks guys.

**Comment by jasonslyvia** [comment]
Should be fixed in 98387254800937a6b167cc4bb7779161e832bafc
