### ISSUE TITLE
"React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead."

### ISSUE THREAD

**Issue by JasonKleban** [jasonslyvia/react-anything-sortable#82]
Prepare for React 16 compatibility.

**Comment by JustFly1984** [comment]
I think we can extend this issue with ```mixin``` property.

It is also deprecated, and it is not possible to use mixins in Pure functional components.

**Comment by JustFly1984** [comment]
I'm sorry, but what about mixin? mixins also deprecated, and whole thing with createReactClass is temporary I hope? It is like you get rid of symptoms instead of curing the sickness. Can you provide better architecture please?

**Comment by jasonslyvia** [comment]
@JustFly1984 This project is no longer actively maintained, thus no architecture refactor will be operated (although PRs are always welcomed)

**Comment by ai** [comment]
React 16 was released ;)

**Comment by spalger** [comment]
Looks like this should have been closed by #83
