### ISSUE TITLE
index.js has a global reference to window, causing server side rendering to crash

### ISSUE THREAD

**Issue by bunkscene** [jasonslyvia/react-anything-sortable#85]
Hi @jasonslyvia,

In 1.7.2, index.js on line 18, there is a reference to "window".  This causes an error when server side rendering a component using react-anything-sortable.  Can you move the window call to a client-only location?

Thanks,
Dave

**Comment by jasonslyvia** [comment]
You mean this line of code https://github.com/jasonslyvia/react-anything-sortable/blob/e789b55dee039400f38303598621f1f965c03672/src/index.js#L18 ?

**Comment by bunkscene** [comment]
Ohhhhh... you fixed it already.  HA, sorry, I did not notice.  Awesome, thanks!
