### ISSUE TITLE
Firefox + IE11 when scrolling is still broken

### ISSUE THREAD

**Issue by bunkscene** [jasonslyvia/react-anything-sortable#89]
Hi,

Firefox is still broken when scrolled down.  I noticed this change seems incorrect:[https://github.com/jasonslyvia/react-anything-sortable/commit/22335c6f80a2dca524da55a4649ec2c5778dab90](https://github.com/jasonslyvia/react-anything-sortable/commit/22335c6f80a2dca524da55a4649ec2c5778dab90)

If you change "docElement" to "documentElement", everything works great.

Thanks,
Dave

**Comment by bunkscene** [comment]
Added pull request: [https://github.com/jasonslyvia/react-anything-sortable/pull/90](https://github.com/jasonslyvia/react-anything-sortable/pull/90)

**Comment by jasonslyvia** [comment]
Great work! #90 is merged and `1.7.3` is released accordingly.
