### ISSUE TITLE
Text in dragging state

### ISSUE THREAD

**Issue by aanchalgera** [jasonslyvia/react-anything-sortable#9]
I am trying to drag textareas with text in them. When I drag them, the text areas are dragged, but the text is not. 
How can I show the text in the textarea in dragging state?

**Comment by jasonslyvia** [comment]
Hi, can you provide a minimal working snippet so I can dive into it ?

**Comment by aanchalgera** [comment]
In the demo code, If I replace {item} with <textarea/> or <div>, I get this error
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
```javascript
 <li data-id={i}
            key={i}
            draggable="true"
            onDragEnd={this.dragEnd}
            onDragStart={this.dragStart}>
         <Content text={item} /> 
        <div className="form-control"></div>
        </li>
```

**Comment by jasonslyvia** [comment]
I'm sorry but I fail to see how you use `react-anything-sortable` component.

**Comment by aanchalgera** [comment]
I am sorry, I think I mixed 2 approaches. I am closing the issue. Thanks!
