### ISSUE TITLE
Grid option

### ISSUE THREAD

**Issue by Rudgey84** [jasonslyvia/react-anything-sortable#91]
Is there a way to have a grid option with this dnd library?

`<Sortable sensitivity={0} key={this.state.data.length} onSort={this.handleSort.bind(this)}>
        {items}
      </Sortable>`

**Comment by jasonslyvia** [comment]
I'm sorry but no feature will be added at this time, I'd recommend you to check out [react-dnd](https://github.com/react-dnd/react-dnd).
