### ISSUE TITLE
Not working on Mobile browser properly.. 

### ISSUE THREAD

**Issue by harvinder-ss** [jasonslyvia/react-anything-sortable#92]
Sort not working on mobile browser when you have a long page. It scroll the page as well as the item and does not seem to be working correctly.

**Comment by jasonslyvia** [comment]
This is more of a feature than an issue, and sorry no new feature will be added at this moment.

**Comment by harvinder-ss** [comment]
Actually I am looking for this: 

https://github.com/jasonslyvia/react-anything-sortable/pull/32

But it does not work on actual devices
